# Generated by Django 3.0.2 on 2020-01-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paste_text', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('pub_user', models.CharField(max_length=30, verbose_name='username')),
            ],
        ),
    ]
