# Generated by Django 3.0.2 on 2020-01-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paste',
            old_name='paste_text',
            new_name='text',
        ),
        migrations.AddField(
            model_name='paste',
            name='title',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
