# Generated by Django 3.0.2 on 2020-01-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0002_auto_20200117_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='pub_user',
            field=models.CharField(default='Guest', max_length=30, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='paste',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='paste',
            name='title',
            field=models.CharField(default='Paste', max_length=15),
        ),
    ]
