# Generated by Django 3.0.2 on 2020-01-20 04:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0003_auto_20200117_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paste',
            name='id',
        ),
        migrations.AddField(
            model_name='paste',
            name='paste_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
